// DEMO

export const GET_DEMOS = "GET_DEMOS";
export const GET_DEMO = "GET_DEMO";
export const CREATE_DEMO = "CREATE_DEMO";
export const UPDATE_DEMO = "UPDATE_DEMO";
export const DELETE_DEMO = "DELETE_DEMO";

// AUTH

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

// APPOINTMENTS

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const CREATE_APPOINTMENT = "CREATE_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";

// DOCTORS

export const GET_DOCTORS = "GET_DOCTORS";
export const GET_DOCTOR = "GET_DOCTOR";
export const CREATE_DOCTOR = "CREATE_DOCTOR";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";

//EMPLOYEES

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SEARCH_EMPLOYEES = "SEARCH_EMPLOYEES";

// EXAMINATIONS

export const GET_EXAMINATIONS = "GET_EXAMINATIONS";
export const GET_EXAMINATION = "GET_EXAMINATION";
export const CREATE_EXAMINATION = "CREATE_EXAMINATION";
export const UPDATE_EXAMINATION = "UPDATE_EXAMINATION";
export const DELETE_EXAMINATION = "DELETE_EXAMINATION";

// RECORDS

export const GET_RECORDS = "GET_RECORDS";
export const GET_RECORD = "GET_RECORD";
export const CREATE_RECORD = "CREATE_RECORD";
export const UPDATE_RECORD = "UPDATE_RECORD";
export const DELETE_RECORD = "DELETE_RECORD";

// PATIENTS

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENT = "GET_PATIENT";
export const CREATE_PATIENT = "CREATE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const SEARCH_PATIENTS = "SEARCH_PATIENTS";

// DEPARTMENTS

export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";

// DISEASES

export const GET_DISEASES = "GET_DISEASES";
export const GET_DISEASE = "GET_DISEASE";
export const CREATE_DISEASE = "CREATE_DISEASE";
export const UPDATE_DISEASE = "UPDATE_DISEASE";
export const DELETE_DISEASE = "DELETE_DISEASE";

// REFERRALS

export const GET_REFERRALS = "GET_REFERRALS";
export const GET_REFERRAL = "GET_REFERRAL";
export const CREATE_REFERRAL = "CREATE_REFERRAL";
export const UPDATE_REFERRAL = "UPDATE_REFERRAL";
export const DELETE_REFERRAL = "DELETE_REFERRAL";

// LAB REPORTS

export const GET_LAB_REPORTS = "GET_LAB_REPORTS";
export const GET_LAB_REPORT = "GET_LAB_REPORT";
export const CREATE_LAB_REPORT = "CREATE_LAB_REPORT";
export const UPDATE_LAB_REPORT = "UPDATE_LAB_REPORT";
export const DELETE_LAB_REPORT = "DELETE_LAB_REPORT";
export const GET_NUMBER_OF_APPOINTMENTS = "GET_NUMBER_OF_APPOINTMENTS";

//LAB VISITS
export const GET_LAB_VISITS = "GET_LAB_VISITS";
export const UPDATE_LAB_VISITS = "UPDATE_LAB_VISITS";
export const CREATE_LAB_VISIT = "CREATE_LAB_VISIT";

//PATIENTS ADMISSIONS
export const GET_PATIENTS_ADMISSIONS = "GET_PATIENTS_ADMISSIONS";
export const UPDATE_PATIENT_ADMISSION = "UPDATE_PATIENT_ADMISSION";
export const CREATE_PATIENT_ADMISSION = "CREATE_PATIENT_ADMISSION";

//HOSPITAL ROOMS
export const GET_HOSPITAL_ROOMS = "GET_HOSPITAL_ROOMS";
