// DEMO

export const GET_DEMOS = "GET_DEMOS";
export const GET_DEMO = "GET_DEMO";
export const CREATE_DEMO = "CREATE_DEMO";
export const UPDATE_DEMO = "UPDATE_DEMO";
export const DELETE_DEMO = "DELETE_DEMO";

// APPOINTMENTS

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const CREATE_APPOINTMENT_NURSE = "CREATE_APPOINTMENT_NURSE";
export const DELETE_APPOINTMENT_NURSE = "DELETE_APPOINTMENT_NURSE";

// DOCTORS

export const GET_DOCTORS = "GET_DOCTORS";
// SCHEDULED APPOINTMENTS

export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
//EMPLOYEES

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const SEARCH_EMPLOYEES = "SEARCH_EMPLOYEES";

// EXAMINATIONS

export const CREATE_EXAMINATION = "CREATE_EXAMINATION";

// RECORDS

export const GET_RECORD = "GET_RECORD";
export const CREATE_RECORD = "CREATE_RECORD";

//PATIENTS
export const GET_PATIENTS = "GET_PATIENTS";
export const SEARCH_PATIENTS = "SEARCH_PATIENTS";
