// DEMO

export const GET_DEMOS = "GET_DEMOS";
export const GET_DEMO = "GET_DEMO";
export const CREATE_DEMO = "CREATE_DEMO";
export const UPDATE_DEMO = "UPDATE_DEMO";
export const DELETE_DEMO = "DELETE_DEMO";

// AUTH

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

// APPOINTMENTS

export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_APPOINTMENT = "GET_APPOINTMENT";
export const CREATE_APPOINTMENT = "CREATE_APPOINTMENT";
export const UPDATE_APPOINTMENT = "UPDATE_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";

// DOCTORS

export const GET_DOCTORS = "GET_DOCTORS";
export const GET_DOCTOR = "GET_DOCTOR";
export const CREATE_DOCTOR = "CREATE_DOCTOR";
export const UPDATE_DOCTOR = "UPDATE_DOCTOR";
export const DELETE_DOCTOR = "DELETE_DOCTOR";

//EMPLOYEES

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const CREATE_EMPLOYEE = "CREATE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SEARCH_EMPLOYEES = "SEARCH_EMPLOYEES";

// EXAMINATIONS

export const GET_EXAMINATIONS = "GET_EXAMINATIONS";
export const GET_EXAMINATION = "GET_EXAMINATION";
export const CREATE_EXAMINATION = "CREATE_EXAMINATION";
export const UPDATE_EXAMINATION = "UPDATE_EXAMINATION";
export const DELETE_EXAMINATION = "DELETE_EXAMINATION";

// RECORDS

export const GET_RECORDS = "GET_RECORDS";
export const GET_RECORD = "GET_RECORD";
export const CREATE_RECORD = "CREATE_RECORD";
export const UPDATE_RECORD = "UPDATE_RECORD";
export const DELETE_RECORD = "DELETE_RECORD";

//PATIENTS

export const GET_PATIENTS = "GET_PATIENTS";
export const GET_PATIENT = "GET_PATIENT";
export const CREATE_PATIENT = "CREATE_PATIENT";
export const UPDATE_PATIENT = "UPDATE_PATIENT";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const SEARCH_PATIENTS = "SEARCH_PATIENTS";
